---
name: "example"
description: >-
  This is an example

https:
  host: "0.0.0.0"
  port: 443
  cross:
    - "example.com"
    - "*.example.com"
  public: "service/static/config/cert/public.pem"
  private: "service/static/config/cert/private.pem"

postgres:
  host: "host"
  port: 5432
  database: "database"
  schema: "schema"
  username: "username"
  password: "password"
...
